// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBysFfJtKHm3cje0pfbnMR23bL3I7QJqWc',
    appId: '1:288893562105:web:d1a0306d97a2160075c628',
    messagingSenderId: '288893562105',
    projectId: 'exchange-9ac12',
    authDomain: 'exchange-9ac12.firebaseapp.com',
    storageBucket: 'exchange-9ac12.appspot.com',
    measurementId: 'G-FQNZGLDZC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gM5n3cc5OvD1BOOwXN6T1aKhHK0oqiU',
    appId: '1:288893562105:android:d99142dc29ad294275c628',
    messagingSenderId: '288893562105',
    projectId: 'exchange-9ac12',
    storageBucket: 'exchange-9ac12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjUOsUOzvS2sTguUp_JGwp3mhejuHBLc',
    appId: '1:288893562105:ios:520ac2f705c1974f75c628',
    messagingSenderId: '288893562105',
    projectId: 'exchange-9ac12',
    storageBucket: 'exchange-9ac12.appspot.com',
    iosBundleId: 'com.example.exchange',
  );
}
