/// 상대교 업데이트 코드
/*
  Map<String, Map<String, String>> sangDaeGyo = {
    '영미권': {
      'Angelo State University': 'https://example.com', // Random URL as placeholder
      'Drexel University': 'https://drexel.edu/global/student-programs/exchange-and-visiting-students/',
      'Georgia State University': 'https://www.studyabroad.gsu.edu/index.cfm?FuseAction=Programs.ViewProgramAngular&id=22176',
      'Kennesaw State University': 'https://www.kennesaw.edu/global-education/international-student-scholar-services/j-1/index.php',
      'LeTourneau University': 'https://www.letu.edu/global-initiatives/exchange-checklist.html',
      'North Carolina State University': 'https://studyabroad.ncsu.edu/incoming-student/',
      'Northern Arizona University': 'https://nau.edu/isss/exchange-students/',
      'Ohio Northern University': 'https://www.onu.edu/admissions-aid/apply-onu',
      'Pittsburg State University': 'https://admission.pittstate.edu/international-admission-information.html#undefined3',
      'Portland State University': 'https://www.pdx.edu/international-students/exchange-students',
      'State University of New York at Oswego': 'https://www.oswego.edu/international/exchange-students',
      'State University of New York at Stony Brook': 'http://stonybrook.edu/studyabroad/incoming',
      'Temple University': 'https://globalprograms.temple.edu',
      'The University of Kansas': 'https://studyabroad.ku.edu/exchangestudents',
      'The University of Texas at Austin': 'https://global.utexas.edu/isss/advising-services/student-exchange-program',
      'University of California, San Diego': 'https://global.ucsd.edu/programs-partnerships/global-exchange-programs/gep-inbound.html',
      'University of Central Oklahoma': 'https://www.uco.edu/student-resources/oga/',
      'University of Nebraska at Kearney': 'https://www.unk.edu/international/Scholars/J-1%20Scholars/j-1-scholar-information.php',
      'University of North Dakota': 'https://und.edu/academics/international-center/international-student-scholar-services/incoming-exchange.html',
      'University of North Texas': 'https://mystudyabroad.unt.edu/?go=INCX',
      'University of Oregon': 'https://isss.uoregon.edu/exchange-visiting-students',
      'University of the Pacific': 'https://example.com/university-of-the-pacific', // Random URL as placeholder
      'Birmingham City University': 'https://www.bcu.ac.uk/international/go-abroad-at-bcu',
      'The University of Leeds': 'https://www.leeds.ac.uk/international-exchange-and-study-abroad',
      'The University of Sheffield': 'https://www.sheffield.ac.uk/globalopps/inbound',
      'University for the Creative Arts': 'https://www.uca.ac.uk/study-at-uca/study-abroad/incoming/',
      'Concordia University': 'https://www.concordia.ca/international/students-from-abroad/inbound-exchange/apply.html',
      'Ecole de Technologie Superieure': 'https://www.etsmtl.ca/etudes/choisir-ets-pour-etudier-en-genie/faire-echange-etudiant',
      'Mount Royal University': 'mru.ca/inbound',
      'Universite de Montreal': 'https://international.umontreal.ca/english/international-students/student-exchange-program/',
      'York University': 'https://yorkinternational.yorku.ca/global-learning/incoming-global-learning/explore-academic-exchange/',
      'Deakin University': 'https://www.deakin.edu.au/international-students/study-abroad-and-exchange',
      'Macquarie University': 'https://www.mq.edu.au/study/information-for/international/study-abroad-exchange-and-study-tours/exchange',
      'Queensland University of Technology': 'https://www.qut.edu.au/study/applying/study-abroad-and-exchange/exchange',
      'The University of New South Wales': 'https://www.unsw.edu.au/study/international-students/study-abroad#studentexchange',
      'The University of Newcastle': 'https://www.newcastle.edu.au/study/international/study-with-us/study-abroad-and-exchange',
      'University of South Australia': 'https://international.unisa.edu.au/short-term-study/',
      'Western Sydney University': 'https://www.westernsydney.edu.au/international/applying/how-to-apply/study-abroad',
    },
    '유럽권': {
      'Amsterdam University of Applied Sciences-CMD(Communication & Multimedia Design)': 'https://cmd-amsterdam.nl/english/international-minors/ website will be updated. Other relevant websites: https://www.amsterdamuas.com/study/information-for/exchange-students',
      'Amsterdam University of Applied Sciences-ICT(IT & Computer Science)': 'https://www.amsterdamuas.com/study/education/exchange/ict',
      'Breda University of Applied Sciences': 'https://www.buas.nl/en/study/exchange-programmes',
      'Erasmus University Rotterdam': 'https://www.eur.nl/en/essb/education/exchange/incoming-exchange',
      'Fontys University of Applied Sciences': 'https://www.fontys.nl/en/Study-at-Fontys/Exchange-programmes.htm',
      'Hanze University of Applied Sciences Groningen': 'www.hanze.nl/hlcc-en',
      'HU University of Applied Sciences Utrecht': 'https://www.internationalhu.com/admissions-exchange',
      'The Hague University of Applied Sciences-Business Finance & Marketing': 'https://www.thuas.com/programmes/exchange-programmes-other-courses/exchange-programmes',
      'The Hague university Of Applied Sciences-Process & Food Technology, Engineering, Industrial Product Design': 'https://www.thuas.com/programmes/exchange-programmes-other-courses/exchange-programmes',
      'University of Twente': 'https://www.utwente.nl/en/education/electives/exchange/',
      'Utrecht University': 'https://www.uu.nl/en/organisation/university-college-utrecht/how-to-apply/exchange-students',
      'IT University of Copenhagen': 'https://en.itu.dk/Programmes/Exchange-students/Become-an-exchange-student-at-ITU',
      'VIA University College': 'https://en.via.dk/programmes/exchange',
      'Esslingen University of Applied Sciences': 'www.hs-esslingen.de/incoming',
      'European University Viadrina': 'https://www.europa-uni.de/en/internationales/Students/Incomings/index.html',
      'International School of Management': 'https://en.ism.de/exchange-students/international-business-certificate',
      'Karlshochschule International University': 'https://karlshochschule.de/en/university/semester-abroad/international-office',
      'Karlsruhe University of Applied Sciences': 'https://www.h-ka.de/en/exchange-students',
      'Konstanz University of Applied Sciences': 'https://www.htwg-konstanz.de/en/academics/international-office/international-students/incoming-exchange-students-from-partner-universities',
      'Pforzheim University': 'https://www.hs-pforzheim.de/en/international/studying_in_pforzheim/exchange_students',
      'Reutlingen University': 'https://www.reutlingen-university.de/en/international/from-abroad',
      'The University of Bamberg': 'https://www.uni-bamberg.de/en/studies/exchange-students-eg-erasmus/',
      'Universitat Konstanz': 'https://www.uni-konstanz.de/en/international-office/study-in-konstanz/exchange-studies/',
      'University of Applied Sciences Neu-Ulm': 'https://www.hnu.de/en/international/international-exchange-students',
      'University of Bayreuth': 'https://www.international-office.uni-bayreuth.de/en/come-to-bayreuth/welcome-services/international-exchange-students/index.html',
      'University of Stuttgart': 'http://www.ia.uni-stuttgart.de/internat/bewerber/program/Overseas/index.en.html',
      'University of Tubingen': 'https://uni-tuebingen.de/en/international/study-in-tuebingen/erasmus-and-exchange-to-tuebingen/',
      'Kaunas University of Technology': 'https://admissions.ktu.edu/exchange-students/',
      'Vilnius Gediminas Technical University': 'https://vilniustech.lt/for-international-students/for-exchange-students/studies/319312?',
      'KU Leuven': 'https://feb.kuleuven.be/eng/international/coming-on-exchange/home',
      'University of Antwerp': 'https://www.uantwerpen.be/en/study/erasmus-and-exchange-students/become-an-exchange-student/',
      'University of Liege': 'https://www.hec.uliege.be/en/incoming-exchange-mobility',
      'Halmstad University': 'https://www.hh.se/english/education/apply-to-halmstad-university/apply-as-exchange-student.html',
      'Linkoping University-Faculty of Arts and Sciences': 'https://liu.se/en/article/application-procedure-faculty-of-arts-and-sciences',
      'Linkoping University-Faculty of Science and Engineering': 'https://liu.se/en/education/exchange-studies',
      'Sodertorn University': 'https://www.sh.se/english/sodertorn-university/student/prospective-students',
      'Umea University': 'https://www.umu.se/en/education/exchange-students/',
      'University of Applied Sciences and Arts Northwestern Switzerland': 'https://www.fhnw.ch/plattformen/iobusiness/',
      'University of St. Gallen': 'https://www.unisg.ch/en/studying/exchange-programme/incoming-guest-students/',
      'Zurich University of Applied Sciences-School of Management and Law': 'https://www.zhaw.ch/en/sml/study/international/incoming-students/',
      'Zurich University of Applied Sciences-School of Engineering': 'https://www.zhaw.ch/en/engineering/study/international-office/incoming-exchange-students/',
      'Universidad Carlos III de Madrid': 'https://www.uc3m.es/studies/international-exchange-students-in-UC3M-/bachelor-degrees',
      'Universidad Catolica de Valencia "San Vicente Martir"': 'https://www.ucv.es/international/exchange-student-at-ucv/our-courses',
      'Universidad Pontificia Comillas': 'https://www.comillas.edu/en/international-relations-service/',
      'Universitat de Barcelona': 'https://www.ub.edu/uri/estudiantsNOUB/intercanvis/welcomeang.htm',
      'Universitat Politecnica de Valencia': 'http://www.upv.es/entidades/OPII/infoweb/pi/info/818856normali.html',
      'University of A Coruna': 'https://www.udc.es/en/ori/infestudantesextranxeiros/mobilidade_Erasmus/guia_acollida_UDC/index.html',
      'University of Lleida': 'https://www.udl.cat/ca/serveis/ori/estudiantat_estranger/eng/mobility/',
      'University of Vic': 'https://www.uvic.cat/en/international/exchange_students',
      'MCI Management Center Innsbruck': 'https://www.mci4me.at/en/international/study-internationally/exchange-students',
      'Catholic University of the Sacred Heart(UCSC)': 'https://international.unicatt.it/ucscinternational-semester-programs-exchange-program-in-milan',
      'Polytechnic University of Milan': 'https://www.polimi.it/en/exchange-students-incoming',
      'Czech Technical University in Prague': 'https://international.cvut.cz/students/incoming-students/erasmus-and-exchange/',
      'Institute of Technology and Business in Ceske Budejovice': 'https://abroad.vstecb.cz/exchange-and-erasmus/student-exchange/application-procedure/',
      'Tomas Bata University in Zlín': 'https://www.utb.cz/en/university/international/students/exchange-students/incoming-students/application/',
      'University of Zagreb': 'https://www.unizg.hr/homepage/international-exchange/exchange-students/',
      'Cracow University of Technology': 'https://iro.pk.edu.pl/incoming-exchange-students/',
      'Audencia Business School': 'https://apply.exchangestudents.audencia.com/_portal/incoming-students',
      'CentraleSupélec': 'https://www.centralesupelec.fr/en/study-centralesupelec',
      'Ecole de Management de Normandie': 'https://en.em-normandie.com/em-normandie-experience/open-world-studying-abroad/exchange-programmes',
      "Ecole Pour L'Informatique et les Techniques Avancees": 'https://sway.office.com/pw0vfIJzSxUAjaxp',
      'ISC Paris': 'https://www.iscparis.com/en/incoming-students/',
      'KEDGE Business School': 'https://student.kedge.edu/exchange-programmes',
      'Pole Universitaire Leonard de Vinci': 'https://www.devinci.fr/en/international/exchange-students/',
      'Rennes School of Business': 'https://www.rennes-sb.com/programmes/exchange-programme/incoming-exchange-students/',
      'Universite Sorbonne Paris Nord': 'https://www.univ-spn.fr/',
      'University of Strasbourg': 'https://international-welcome.unistra.fr/',
      'University Paris 8': 'https://www.univ-paris8.fr/-Vous-venez-avec-un-programme-d-echanges-',
      'Haaga-Helia University of Applied Sciences': 'https://www.haaga-helia.fi/en/exchange-studies-haaga-helia',
      'Hanken School of Economics': 'https://www.hanken.fi/en/apply/international-opportunities/incoming-exchange-students',
    },
    '기타': {
      'GE3 (Global Engineering Education Exchange)': 'https://globale3.studioabroad.com/',
      'ISEP (International Student Exchange Programs)': 'http://www.isepstudyabroad.org',
      'University of Malaya': 'https://gem.um.edu.my/inbound-long-term-home',
      'Tecnologico de Monterrey': 'https://studyinmexico.tec.mx',
      'Universidad Nacional Autonoma de Mexico': 'https://www.unaminternacional.unam.mx/en/blog/la-movilidad',
      'Universite Internationale de Rabat': 'https://www.uir.ac.ma/fr/pole/international',
      'Pontificia Universidade Catolica de Minas Gerais': 'https://portal.pucminas.br/ari/index_padrao.php?pagina=2308',
      'Nanyang Technological University': 'https://gem.ntu.edu.sg/index.cfm?FuseAction=Programs.ViewProgramAngular&id=10006',
      'Singapore University of Technology and Design': 'https://sutd.edu.sg/Student-Development/Global/Student-Exchange/Inbound/Inbound-Exchange',
      'Austral University': 'https://drive.google.com/drive/folders/1pTyx_0wy8NmDX5Rs6Ql2faerjL6hioT0?hl=es',
      'Universitas Indonesia': 'https://international.ui.ac.id/exchange/',
      'KIMEP University': 'https://www.kimep.kz/diam/en/academic-mobility-for-incoming-students/',
      'City University of Hong Kong': 'http://www.cityu.edu.hk/class/exchange/content/inbound/course_info.aspx',
      'Hang Seng University of Hong Kong': 'https://gao.hsu.edu.hk/en/inbound-exchange/',
      'Lingnan University': 'https://www.ln.edu.hk/oge/incoming_stu/',
      'The Chinese University of Hong Kong': 'https://www.oal.cuhk.edu.hk/getting_started/',
      'The Hong Kong Polytechnic University': 'https://www.polyu.edu.hk/geo/exchange-and-study-abroad/incoming-students/incoming-exchange/',
    },
    '일본어권': {
      'Waseda University': 'https://www.waseda.jp/inst/cie/en/exchange',
      'Hokkaido University': 'https://www.global.hokudai.ac.jp/admissions/exchange-student-admissions/',
      'Kansai University': 'https://www.kansai-u.ac.jp/Kokusai/future/',
      'Konan University': 'https://www.konan-u.ac.jp/kiec/',
      'Kwansei Gakuin University': 'https://ciec.kwansei.ac.jp/study/exchange/',
      'Meiji University': 'https://www.meiji.ac.jp/cip/english/admissions/exchange.html',
      'Musashino University': 'https://www.musashino-u.ac.jp/en/for_students/study_abroad/criteria.html',
      'Nagasaki University of Foreign Studies': 'https://www.nagasaki-gaigo.ac.jp/studying-abroad/receiving_program/nics_program/?lang=kr',
      'Nagoya Institute of Technology': 'https://www.nitech.ac.jp/eng/admission/exchange.html',
      'Niigata University': 'https://www.niigata-u.ac.jp/en/study/exchange/',
      'Ritsumeikan Asia Pacific University': 'https://en.apu.ac.jp/abroad/prospective/incoming/',
      'Shinshu University': 'https://www.shinshu-u.ac.jp/institution/gec/en/prospective_students/gec_exchange_student_program/',
      'Sophia University': 'http://www.sophia-cler.jp/study/ja/',
      'Tama University': 'https://www.tama.ac.jp/international/smis/incomng.html',
      'Tokyo Institute of Technology': 'https://www.titech.ac.jp/english/international-student-exchange/prospective-students/non-degree',
      'University of Fukui': 'https://www.u-fukui.ac.jp/eng/inbound/exchange/',
    },
    '중국어권': {
      'Feng Chia University': 'https://oia.fcu.edu.tw/en/overseas-students/inbound_international/',
      'National Chengchi University': 'https://oic.nccu.edu.tw/',
      'National Taiwan University': 'https://oia.ntu.edu.tw/en/internationalstudents/exchange/overview',
      'National Taiwan University of Arts': 'https://international.ntua.edu.tw/article/detail/webSN/125/sn/480',
      'National Taiwan University of Science and Technology': 'https://oia-r.ntust.edu.tw/p/412-1060-8919.php?Lang=en',
      'National University of Kaohsiung': 'https://dia.nuk.edu.tw/p/412-1034-4611.php?Lang=zh-tw',
      'National Yang Ming Chiao Tung University': 'https://oia.nycu.edu.tw/oia/en/app/artwebsite/view?module=artwebsite&id=821&serno=a277c341-8d25-4a51-8495-58d1d58bbc5d',
      'Soochow University': 'https://icae.scu.edu.tw/en/incoming/intro',
      'Tamkang University': 'http://www.oieie.tku.edu.tw/?locale=en',
      'Beijing Institute of Technology': 'https://isc.bit.edu.cn/admissionsaid/essap/internationalexchange/index.htm',
      'Beijing Normal University': 'https://international.bnu.edu.cn/user/login',
      'Chongqing University': 'http://study.cqu.edu.cn/info/1383/1633.htm',
      'Dalian University of Technology': 'http://dutdice.dlut.edu.cn/en/index.htm',
      'East China Normal University': 'http://lxs.ecnu.edu.cn/cn/admission/exchange-programs/programs-introduction',
      'Harbin Institute of Technology': 'http://studyathit.hit.edu.cn/ExchangeProgram/list.htm',
      'Jilin University': 'cie.jlu.edu.cn',
      'Shandong University at Weihai': 'https://ipo.wh.sdu.edu.cn/kristudy/lxxm1/jhsxm.htm',
      'South China University of Technology': 'http://sie.scut.edu.cn/main.htm',
      'The Chinese University of Hong Kong, Shenzhen': 'https://oal.cuhk.edu.cn/en/incoming_students',
    }
  };
  void univAdder() async {
    await FirebaseFirestore.instance.collection('universities').doc('한양대학교').update({
      '상대교' : sangDaeGyo,
    });
  }
  @override
  void initState() {
    super.initState();
    univAdder();
  }
  */